### ISSUE TITLE
Support for not4plebs.org and fgts.jp/b/

### ISSUE THREAD

**Issue by usernamestring** [SuperGouge/ChanThreadWatch#45]
Hi. Thanks for adding support for archive sites, it's a feature I always wanted.
I have tried CTW with a bunch of archivers that use the foolfuka code with no problem, except for this new archiver called not4plebs:
https://totally.not4plebs.org/sp/
There's something different with this board that prevents CTW from fetching full images and thumbnails but I can't figure what it is. Can this be fixed?

Also fgts.jp recently started archiving /b/, but access to the archive is a bit tricky, you need to connect to their IRC channel, accept a cookie and keep it until you leave the site. I was wondering if there's a way to make CTW somehow detect these settings and be able to download threads from their /b/ archive.

Thank you and thanks for the last update.

**Comment by SuperGouge** [comment]
I manually add known archive sites using https://github.com/MayhemYDG/archives.json. This site didn't exist when I added them but I will add it for the next release.

As for fgts.jp's /b/ archive, I don't think it will be supported for a while because that would require a substantial amount of code reorganization just for that specific board.
