### ISSUE TITLE
Documentation/Wiki missing important information

### ISSUE THREAD

**Issue by Hrxn** [SuperGouge/ChanThreadWatch#61]
It has a pretty exhaustive [feature page](https://github.com/SuperGouge/ChanThreadWatch/wiki/Features), but I think there is something missing.

To be specific, I just couldn't find anything about which sites or image boards are actually supported.

I mean, how are we supposed to know? :-)

**Comment by jwshields** [comment]
CTW should work on _most_ all Futaba/Futallaby, Wakaba, Kusaba, TinyIB, and Yostuba based imageboards. I think I've seen it work on some unknown ones like drydock and whatnot. 
Because there are so many different BBS/IB sites out there I don't think it would be worth it to list them; but knowing the backend would give you a clue to what sites it would work on. (fwiw- the ones, futaba, wakaba, etc list at the bottom of a board what software it is)
