### ISSUE TITLE
CTW Speed limiter broken?

### ISSUE THREAD

**Issue by 2mg** [SuperGouge/ChanThreadWatch#65]
Limit at 100KBps, huge bandwidth spikes, see attached image.

![ctw](https://cloud.githubusercontent.com/assets/7749968/15807338/c49c3c26-2b5b-11e6-9ba2-7543e98fc82e.jpg)

**Comment by 2mg** [comment]
Bump

**Comment by SuperGouge** [comment]
Hello, sorry for the late response.

The way this function works is it actually tries to reduce the speed when it sees values exceeding your limit to adjust. Unfortunately, due to the nature of the downloads and the way this throttling works, spikes are bound to happen. However you should see that the average over even a very short period of time should not exceed your limit.

As far as I know there is no way to achieve something more accurate without using some low level APIs and/or using a custom network adapter. But if someone knows a simpler way please let me know.

I realize these spikes can be annoying but this is the best solution I'm able to offer to the bandwidth throttling feature that was requested. Sorry for the inconvenience.

**Comment by 2mg** [comment]
Thanks for responding!

I just saw this mail, and bumped my issue earlier so just close it.

I can live with spikes, I just set the limit lower, though I'd just thought
it would be good to ask a dev. Keep it updated, glorious job.
